server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      force-response: true

  shutdown: graceful

  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log

spring:
  datasource:
    url: jdbc:mysql://bbanggle-dev-db.cehfb4mzdov6.ap-northeast-2.rds.amazonaws.com:3306/bbanggle?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: admin
    password: Dhfkzmf0417!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql : true # sql ??? ??
        default_batch_fetch_size: 1000

    show-sql: true  # sql
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB # ?? ??? ?? ? ??? ?? ?? 10MB? ??
      max-request-size: 100MB # ?? ??? ?? ? ?? ??? ???? 100MB? ??

logging:
  level:
    org.hibernate.type: trace

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

token:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJYOUR_SECRET_KEYpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  access-token-expiration-time: 900000  # 15분: 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주: 1000(ms) x 60(s) x 60(m) x 24(h) x 14(d)